# Generated by Django 4.1.7 on 2023-03-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(default='Experience', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='Full Name', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(default='Occupation', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(default='00000', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
